# ----------- Build Stage -----------
FROM node:20 AS build

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build production files
RUN npm run build


# ----------- Production Stage -----------
FROM nginx:alpine

# Copy dist output to nginx folder
COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose NGINX default port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
