FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (without dev dependencies)
RUN npm install --omit=dev

# Copy the rest
COPY . .

# Expose backend port
EXPOSE 5002

# Start the app
CMD ["node", "index.js"]
